### ISSUE TITLE
vscode complains that setting "groovyLint.fix.trigger": "user" should be a boolean

### ISSUE THREAD

**Issue by unitysipu** [nvuillam/vscode-groovy-lint#47]
When configuring groovyLint.fix.trigger property in settings, vscode complains that the type is supposed to be a boolean.  

"groovyLint.fix.trigger": "user"

{
	"resource": "/home/simop/.config/Code/User/settings.json",
	"owner": "_generated_diagnostic_collection_name_#5",
	"severity": 4,
	"message": "Incorrect type. Expected \"boolean\".",
	"startLineNumber": 39,
	"startColumn": 31,
	"endLineNumber": 39,
	"endColumn": 37
}

Setting it to a boolean value, vscode complains it should be "user" or "onSave"

"groovyLint.fix.trigger": true
{
	"resource": "/home/simop/.config/Code/User/settings.json",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": "1",
	"severity": 4,
	"message": "Value is not accepted. Valid values: \"onSave\", \"user\".",
	"startLineNumber": 39,
	"startColumn": 31,
	"endLineNumber": 39,
	"endColumn": 35
}

I can't get this plugin to operate and I'm not sure how to fix the issue.

Running vscode on ubuntu 20 LTS
code --version
1.45.1
5763d909d5f12fe19f215cbfdd29a91c0fa9208a
x64

**Comment by terryterryd** [comment]
You can get around it by going to user setting and removing "groovyLint.fix.trigger": false and, instead setting "groovyLint.lint.trigger": "onSave"
Also available by the GUI editor in VS Code (ignore the red block, and set the lint trigger below)

**Comment by nvuillam** [comment]
Simple error in the settings configs, i defined the property as boolean,  it will be corrected in the next release, thanks for reporting the error :)
![image](https://user-images.githubusercontent.com/17500430/83025083-2a314300-a02f-11ea-81f7-7e96e4c8288e.png)

**Comment by unitysipu** [comment]
nice, knowing what to look for i could patch that value from package.json on disk to "string" type so the error went away. 

I'm still not getting any results to my "problems" view  on vscode though, i'm sure there are some, as the npm-groovy-lint reports quite a few when run from command line.

**Comment by nvuillam** [comment]
@unitysipu maybe you code perfectly :-p

please can you have a look in  Output / GroovyLint and attach me the log ?

**Comment by unitysipu** [comment]
Haha, this isn't my code and I was hoping to use your fantastic tool to improve it! :)
I'll look into providing you with more info tomorrow when i get back to work.

**Comment by nvuillam** [comment]
0.16.2 is online, the fix.trigger setting is fixed :)
If you still have the linting problem, plz can you open a new issue ? thanks !

**Comment by unitysipu** [comment]
I figured out what the issue is: the linting error level was set to "error", not 100% sure if it was set by me or not, but setting it back to info revealed the issues in the problems page.

**Comment by nvuillam** [comment]
Default is info, it must have been you 😅
Have a nice day :)

**Comment by unitysipu** [comment]
You too, thanks for the fix!
